### ISSUE TITLE
errors in crontab file, can't install.

### ISSUE THREAD

**Issue by SaltNego** [WangYihang/Reverse-Shell-Manager#2]
errors in crontab file, can't install.

[192.168.1.241:57692] >> cronadd
Input new crontab task (* * * * * date): echo 1111 >> 1.txt
[+] Saving old crontab
no crontab for root
[+] Receving data from socket...
[+] [FakeTerminal] >> crontab -l > /tmp/o7eTBluDvsGSMXDgRHGwYocpC3RpOPgG-system.server-9QwlFAFg

[+] Add new tasks : echo 1111 >> 1.txt

[+] Rescuing crontab file...
[+] Deleting temp file...
[FakeTerminal] >> 
[192.168.1.241:57692] >> "/tmp/o7eTBluDvsGSMXDgRHGwYocpC3RpOPgG-system.server-9QwlFAFg":0: bad minute
errors in crontab file, can't install.

**Comment by WangYihang** [comment]
oh, i think there is a mistake in your input, you can see the hint text: '* * * * * date', your input format must be like this, the stars can figure out the frequency of the following command, so, you can try this:
* * * * * echo 111 > /tmp/1.txt
the command will be executed every minutes
