### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by 0xa-saline** [WangYihang/Reverse-Shell-Manager#4]
Traceback (most recent call last):
  File "Reverse-Shell-Manager.py", line 470, in <module>
    main()
  File "Reverse-Shell-Manager.py", line 339, in main
    slaves[key].show_info()
  File "Reverse-Shell-Manager.py", line 129, in show_info
    Log.info("ISP : %s-%s" % (self.country, self.isp))
  File "/tmp/Reverse-Shell-Manager/utils/log.py", line 18, in info
    Log._print("[+] %s\n" % color.lightPurple(word))
  File "/tmp/Reverse-Shell-Manager/utils/log.py", line 13, in _print
    sys.stdout.write(word)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 15-16: ordinal not 
in range(128)

**Comment by WangYihang** [comment]
Hi, saline
thank you for your issue, could you tell me more information about this bug ?
such as , linux kernel version, python version and so on...
that will help to recurrent this bug, thank you so much

**Comment by WangYihang** [comment]
I think I find the reason
You can check your linux enviroment
```
LC_TYPE=C
```
I got the same error when I set the var 'LC_TYPE=C'
To solve this problem, just unset all vars like 'LC_*'
then set LC_ALL=en_US.UTF-8
You can see  this question on StackOverflow : 
> https://stackoverflow.com/questions/9942594/unicodeencodeerror-ascii-codec-cant-encode-character-u-xa0-in-position-20/20334767
